# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: agent.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "fastlane_c_i.Log" do
    optional :message, :string, 1
    optional :level, :enum, 2, "fastlane_c_i.Log.Level"
    optional :status, :int32, 3
  end
  add_enum "fastlane_c_i.Log.Level" do
    value :DEBUG, 0
    value :INFO, 1
    value :WARN, 2
    value :ERROR, 3
    value :FATAL, 5
  end
  add_message "fastlane_c_i.Command" do
    optional :bin, :string, 1
    repeated :parameters, :string, 2
    map :env, :string, :string, 3
  end
end

module FastlaneCI
  Log = Google::Protobuf::DescriptorPool.generated_pool.lookup("fastlane_c_i.Log").msgclass
  Log::Level = Google::Protobuf::DescriptorPool.generated_pool.lookup("fastlane_c_i.Log.Level").enummodule
  Command = Google::Protobuf::DescriptorPool.generated_pool.lookup("fastlane_c_i.Command").msgclass
end
