# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: agent.proto for package 'fastlane_c_i'
# Original file comments:
# *
# proto definitions for auto-generated client, server, and messages to pass using grpc.
#
# if you make any changes to this file, run
#   `rake proto`
# to regenerate the ruby code.
#

require 'grpc'
require 'agent_pb'

module FastlaneCI
  module Agent
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'fastlane_c_i.Agent'

      rpc :Spawn, Command, stream(Log)
    end

    Stub = Service.rpc_stub_class
  end
end
