# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: agent.proto for package 'FastlaneCI.Proto'
# Original file comments:
# *
# proto definitions for auto-generated client, server, and messages to pass using grpc.
#
# if you make any changes to this file, run
#   `rake generate_protos`
# to regenerate the ruby code.
#

require 'grpc'
require 'agent_pb'

module FastlaneCI
  module Proto
    module Agent
      class Service

        include GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'FastlaneCI.Proto.Agent'

        rpc :RunFastlane, InvocationRequest, stream(InvocationResponse)
      end

      Stub = Service.rpc_stub_class
    end
  end
end
