# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: runner.proto for package 'fastlane_c_i'

require "grpc"
require "runner_pb"

module FastlaneCI
  module Runner
    class Service
      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = "fastlane_c_i.Runner"

      rpc :Spawn, Command, stream(Log)
    end

    Stub = Service.rpc_stub_class
  end
end
