require "securerandom"

module FastlaneCI

  # Represents a single unit of data generated by a build
  class Artifact

    # @return [UUID] The id of the artifact.
    attr_accessor :id

    # @return [String] The type or kind of artifact.
    attr_accessor :type

    # @return [String] The reference to the artifact to a certain ArtifactProvider
    attr_accessor :reference

    # @return [ArtifactProvider] The reference to the ArtifactProvider that stores the artifact
    attr_accessor :provider

    def initialize(type: nil, provider: nil, id: nil)
      self.type = type
      self.provider = provider
      self.id = id || SecureRandom.uuid
    end
  end
end
