module FastlaneCI
  # Represents a build, part of a project, usually many builds per project
  # One build is identified using the `build.project.id` + `build.number`
  class Build
    # Note, BUILD_STATUSES determine how a build is persisted and how the information is pushed to remote.
    # Example: on success/failure/pending, we automatically update status local + remote
    # SPECIAL NOTE: on `other` the build runner subclass is expected to handle finalization and calling of
    # complete_run(start_time:, artifact_paths: []) in `build_runner.rb`
    # This is confusing, and annoying, but there are weird errors that happen and we need to persist them
    # somehow.
    BUILD_STATUSES = [
      :success,
      :pending,
      :other, # For when things happen like missing Fastfile, or whatever, need a custom error for this
      :failure
    ]

    # A reference to the project this build is associated with
    attr_accessor :project

    # @return [Integer]
    attr_accessor :number

    # @return [String]
    attr_reader :status

    # @return [DateTime] Start time
    attr_accessor :timestamp

    # @return [Integer]
    attr_accessor :duration

    # @return [String] The git sha of the commit this build was run for
    attr_accessor :sha

    # @return [Array(Artifact)] The artifacts generated by the build.
    attr_accessor :artifacts

    # @return [String] An optional message to go along with the build
    attr_accessor :message

    def initialize(project: nil, number: nil, status: nil, timestamp: nil, duration: nil, sha: nil, message: nil)
      self.project = project
      self.number = number
      self.status = status
      self.timestamp = timestamp
      self.duration = duration
      self.sha = sha
      self.artifacts = []
      self.message = message
    end

    def status=(new_value)
      return if new_value.nil? # as during init we might init with 0 when filling in JSON values
      new_value = new_value.to_sym
      raise "Invalid build status '#{new_value}'" unless BUILD_STATUSES.include?(new_value)
      @status = new_value
    end
  end
end
