require_relative "configuration/configuration_controller"
require_relative "dashboard/dashboard_controller"
require_relative "login/login_controller"
require_relative "notifications/notifications_controller"
require_relative "onboarding/onboarding_controller"
require_relative "project/project_controller"
require_relative "build/build_controller"
