require "rake/clean"
require "tmpdir"

module Env
  def self.method_missing(method_name)
    ENV.fetch(method_name.to_s) # fetch throws an error if the key is undefined. This is the behavior we want.
  end
end

task :temp_dir do
  dir = Dir.mktmpdir("fastlane-ci")
  Dir.chdir(dir)
end
CLEAN.add(File.join(Dir.tmpdir, "fastlane-ci*"))

task git_clone: :temp_dir do
  sh "git clone --depth 1 #{Env.GIT_URL} repo"
  Dir.chdir("repo")
end

task :bundler do
  sh "gem install bundler --no-doc"
  sh "bundle install --deployment"
end

task :cocoapods do
  sh "gem install cocoapods --no-doc"
  sh "pod install"
end

desc("run a fastlane action")
task :fastlane, [:action] => [:git_clone, :bundler, :cocoapods] do |t, args|
  sh "bundle exec fastlane #{args.action}"
end